# Generated by Django 5.0.4 on 2024-04-21 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='AdCategory',
        ),
        migrations.RemoveField(
            model_name='lastsentdate',
            name='subscription',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user',)},
        ),
        migrations.AddField(
            model_name='subscription',
            name='categories',
            field=models.ManyToManyField(to='board.adcategory'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AdSubscription',
        ),
        migrations.DeleteModel(
            name='LastSentDate',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='category',
        ),
    ]
