# Generated by Django 5.0.4 on 2024-04-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_category_adcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='categories',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdCategory',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
