# Generated by Django 5.0.4 on 2024-04-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_subscription_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatepage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='responsefilter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PrivatePage',
        ),
        migrations.DeleteModel(
            name='ResponseFilter',
        ),
    ]
